--- 
  - name: Set {{ xander_user }} user authorized key taken from file {{ local_ssh_pub_key }}
    authorized_key:
      user: "{{ xander_user }}"
      state: present
      key: "{{ lookup('file', '{{ local_ssh_pub_key }}') }}"

  - name: Create a SSH key for user {{ xander_user }} in ~{{ xander_user }}/{{ remote_ssh_key_file }}
    user:
      name: "{{ xander_user }}"
      generate_ssh_key: yes
      ssh_key_file: "{{ remote_ssh_key_file }}"

  - name: Copy created SSH key from remote
    fetch:
      src: "{{ xander_home }}/{{ remote_ssh_pub_key_file }}"
      dest: "{{ playbook_dir }}/remote_keys/{{ inventory_dir | basename }}/{{ inventory_hostname }}.pub"
      flat: yes

  - name: Set {{ xander_user }} user authorized key taken from file {{ pipeline_ssh_pub_key }} | Bitbucket Pipeline key
    authorized_key:
      user: "{{ xander_user }}"
      state: present
      key: "{{ lookup('file', '{{ pipeline_ssh_pub_key }}') }}"
    when: pipeline_ssh_pub_key is defined

  - name: Ensure known_hosts file exists
    stat:
      path: "{{ known_hosts_path }}"
    register: known_hosts_check

  - name: Create known_hosts
    file: 
      path: "{{ known_hosts_path }}"
      owner: "{{ xander_user }}"
      group: "{{ xander_group }}"    
      mode: 0666
      state: touch
    when: known_hosts_check.stat.exists == false 

  - name: Add bitbucket.org fingerprint to known_hosts
    shell: ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
    when: known_hosts_check.stat.exists == false 
    become: false
    vars:
      ansible_user: "{{ xander_user }}"

  
